#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MVC5.Web;
    using StackExchange.Profiling;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Administrator/Views/Setting/_UserSetting.cshtml")]
    public partial class _Areas_Administrator_Views_Setting__UserSetting_cshtml : System.Web.Mvc.WebViewPage<MVC5.ViewModel.AdminArea.Setting.UserSettingViewModel>
    {
        public _Areas_Administrator_Views_Setting__UserSetting_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 5 "..\..\Areas\Administrator\Views\Setting\_UserSetting.cshtml"
       Write(Html.LabelFor(m => m.NewsletterEnabled, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 7 "..\..\Areas\Administrator\Views\Setting\_UserSetting.cshtml"
           Write(Html.CheckBoxFor(m => m.NewsletterEnabled, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 11 "..\..\Areas\Administrator\Views\Setting\_UserSetting.cshtml"
       Write(Html.LabelFor(m => m.DefaultAvatarEnabled, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 13 "..\..\Areas\Administrator\Views\Setting\_UserSetting.cshtml"
           Write(Html.CheckBoxFor(m => m.DefaultAvatarEnabled, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 17 "..\..\Areas\Administrator\Views\Setting\_UserSetting.cshtml"
       Write(Html.LabelFor(m => m.DateOfBirthEnabled, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 19 "..\..\Areas\Administrator\Views\Setting\_UserSetting.cshtml"
           Write(Html.CheckBoxFor(m => m.DateOfBirthEnabled, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 23 "..\..\Areas\Administrator\Views\Setting\_UserSetting.cshtml"
       Write(Html.LabelFor(m => m.HideNewsletterBlock, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 25 "..\..\Areas\Administrator\Views\Setting\_UserSetting.cshtml"
           Write(Html.CheckBoxFor(m => m.HideNewsletterBlock, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 29 "..\..\Areas\Administrator\Views\Setting\_UserSetting.cshtml"
       Write(Html.LabelFor(m => m.AvatarMaximumSizeBytes, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 31 "..\..\Areas\Administrator\Views\Setting\_UserSetting.cshtml"
           Write(Html.TextBoxFor(m => m.AvatarMaximumSizeBytes, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 35 "..\..\Areas\Administrator\Views\Setting\_UserSetting.cshtml"
       Write(Html.LabelFor(m => m.NotifyNewUserRegistration, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 37 "..\..\Areas\Administrator\Views\Setting\_UserSetting.cshtml"
           Write(Html.CheckBoxFor(m => m.NotifyNewUserRegistration, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 41 "..\..\Areas\Administrator\Views\Setting\_UserSetting.cshtml"
       Write(Html.LabelFor(m => m.ShowUsersJoinDate, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 43 "..\..\Areas\Administrator\Views\Setting\_UserSetting.cshtml"
           Write(Html.CheckBoxFor(m => m.ShowUsersJoinDate, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        \r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 48 "..\..\Areas\Administrator\Views\Setting\_UserSetting.cshtml"
       Write(Html.LabelFor(m => m.AllowUsersToChangeUsername, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 50 "..\..\Areas\Administrator\Views\Setting\_UserSetting.cshtml"
           Write(Html.CheckBoxFor(m => m.AllowUsersToChangeUsername, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 54 "..\..\Areas\Administrator\Views\Setting\_UserSetting.cshtml"
       Write(Html.LabelFor(m => m.AllowUsersToUploadAvatars, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 56 "..\..\Areas\Administrator\Views\Setting\_UserSetting.cshtml"
           Write(Html.CheckBoxFor(m => m.AllowUsersToUploadAvatars, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 60 "..\..\Areas\Administrator\Views\Setting\_UserSetting.cshtml"
       Write(Html.LabelFor(m => m.UserRegistrationType, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 62 "..\..\Areas\Administrator\Views\Setting\_UserSetting.cshtml"
           Write(Html.EditorFor(m => m.UserRegistrationType, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 66 "..\..\Areas\Administrator\Views\Setting\_UserSetting.cshtml"
       Write(Html.LabelFor(m => m.UserNameFormat, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 68 "..\..\Areas\Administrator\Views\Setting\_UserSetting.cshtml"
           Write(Html.EditorFor(m => m.UserNameFormat, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 72 "..\..\Areas\Administrator\Views\Setting\_UserSetting.cshtml"
       Write(Html.LabelFor(m => m.AllowViewingProfiles, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 74 "..\..\Areas\Administrator\Views\Setting\_UserSetting.cshtml"
           Write(Html.CheckBoxFor(m => m.AllowViewingProfiles, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 78 "..\..\Areas\Administrator\Views\Setting\_UserSetting.cshtml"
       Write(Html.LabelFor(m => m.UsernamesEnabled, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 80 "..\..\Areas\Administrator\Views\Setting\_UserSetting.cshtml"
           Write(Html.CheckBoxFor(m => m.UsernamesEnabled, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
