#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/UserMailer/ConfirmAccount.cshtml")]
    public partial class _Views_UserMailer_ConfirmAccount_cshtml : System.Web.Mvc.WebViewPage<MVC5.ViewModel.Account.EmailViewModel>
    {
        public _Views_UserMailer_ConfirmAccount_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("<p>");

            
            #line 4 "..\..\Views\UserMailer\ConfirmAccount.cshtml"
Write(Model.Message);

            
            #line default
            #line hidden
WriteLiteral(" </p>\r\n\r\n<a");

WriteAttribute("href", Tuple.Create(" href=\"", 94), Tuple.Create("\"", 111)
            
            #line 6 "..\..\Views\UserMailer\ConfirmAccount.cshtml"
, Tuple.Create(Tuple.Create("", 101), Tuple.Create<System.Object, System.Int32>(Model.Url
            
            #line default
            #line hidden
, 101), false)
);

WriteLiteral("><strong>");

            
            #line 6 "..\..\Views\UserMailer\ConfirmAccount.cshtml"
                        Write(Model.UrlText);

            
            #line default
            #line hidden
WriteLiteral("</strong></a>\r\n");

        }
    }
}
#pragma warning restore 1591
