#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/UserMailer/ResetPassword.cshtml")]
    public partial class _Views_UserMailer_ResetPassword_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_UserMailer_ResetPassword_cshtml()
        {
        }
        public override void Execute()
        {
        }
    }
}
#pragma warning restore 1591
