#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Emails/EmailConfirm.cshtml")]
    public partial class _Views_Emails_EmailConfirm_cshtml : System.Web.Mvc.WebViewPage<MVC5.ViewModel.Email.EmailConfirmEmail>
    {
        public _Views_Emails_EmailConfirm_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Emails\EmailConfirm.cshtml"
  
    Layout = "~/Views/Emails/_EmailLayout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("Headers", () => {

WriteLiteral("\r\n    To:  ");

            
            #line 7 "..\..\Views\Emails\EmailConfirm.cshtml"
    Write(Model.To);

            
            #line default
            #line hidden
WriteLiteral("\r\n    Subject: فعال سازی حساب کاربری\r\n    Content-Type: text/html; charset=utf-8\r" +
"\n");

});

WriteLiteral("\r\n<p>\r\n    برای فعال سازی حساب خود بر روری لینک مقابل کلیک کنید\r\n    \r\n</p>\r\n<a");

WriteAttribute("href", Tuple.Create(" href=\"", 310), Tuple.Create("\"", 328)
            
            #line 16 "..\..\Views\Emails\EmailConfirm.cshtml"
, Tuple.Create(Tuple.Create("", 317), Tuple.Create<System.Object, System.Int32>(Model.Link
            
            #line default
            #line hidden
, 317), false)
);

WriteLiteral(">فعال سازی</a>\r\n<a");

WriteAttribute("href", Tuple.Create(" href=\"", 347), Tuple.Create("\"", 365)
            
            #line 17 "..\..\Views\Emails\EmailConfirm.cshtml"
, Tuple.Create(Tuple.Create("", 354), Tuple.Create<System.Object, System.Int32>(Model.Link
            
            #line default
            #line hidden
, 354), false)
);

WriteLiteral(">");

            
            #line 17 "..\..\Views\Emails\EmailConfirm.cshtml"
                 Write(Model.Link);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
