#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\_Toastr.cshtml"
    using MVC5.Common.Controller.Alerts;
    
    #line default
    #line hidden
    using MVC5.ViewModel;
    using MVC5.Web;
    
    #line 2 "..\..\Views\Shared\_Toastr.cshtml"
    using MVC5.Web.RazorHelpers;
    
    #line default
    #line hidden
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Toastr.cshtml")]
    public partial class _Views_Shared__Toastr_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Toastr_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Shared\_Toastr.cshtml"
 if (TempData.ContainsKey(ToastMessage.TempDataKey))
{
    var toastr = TempData[ToastMessage.TempDataKey] as Toastr;
    
            
            #line default
            #line hidden
            
            #line 6 "..\..\Views\Shared\_Toastr.cshtml"
Write(ToastrBuilder.ShowToastMessages(toastr));

            
            #line default
            #line hidden
            
            #line 6 "..\..\Views\Shared\_Toastr.cshtml"
                                            ;
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
