#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Lockout.cshtml")]
    public partial class _Views_Shared_Lockout_cshtml : System.Web.Mvc.WebViewPage<System.Web.Mvc.HandleErrorInfo>
    {
        public _Views_Shared_Lockout_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Shared\Lockout.cshtml"
  
    ViewBag.Title = "Locked Out";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<hgroup>\r\n    <h1");

WriteLiteral(" class=\"text-error\"");

WriteLiteral(">Locked out.</h1>\r\n    <h2");

WriteLiteral(" class=\"text-error\"");

WriteLiteral(">This account has been locked out, please try again later.</h2>\r\n</hgroup>\r\n");

        }
    }
}
#pragma warning restore 1591
