#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MVC5.ViewModel;
    using MVC5.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Index.cshtml")]
    public partial class _Views_Home_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Home_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Home\Index.cshtml"
  
    ViewBag.Title = "Home Page";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n                <strong>طراحی یک فریمورک برای کار با Asp.net MVC , EF</strong>" +
"\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(" style=\"min-height: 300px;\"");

WriteLiteral(@">
                خیلی علاقه مند بودم با افرادی که توانایی کار های بزرگ را دارند ولی تنهایی کار میکنند ، به صورت گروهی یک کار بزرگ را شروع کنیم
                ولی خب اکثرا مشغول هستند.
                هدف بنده ساخت یک قالب پایه برای پروژه ها تحت وب بود که تا الان که ورژن 1.0.0.0 
                آن منتشر میشود ، کم و بیش به این هدف رسیدم . اگر دوستان علاقه به تکمیل کار بنده و آقای سید مجتبی حسینی دارند 
                ، میتوانند در سایت 
                <a");

WriteLiteral(" href=\"http://www.dotnettips.info\"");

WriteLiteral(">.NET Tips </a>\r\n                ما را همراهی کنند.\r\n            </div>\r\n        " +
"    <div");

WriteLiteral(" class=\"panel-footer\"");

WriteLiteral(">\r\n                <strong>\r\n                    غلامرضا ربال-دانشجوی ترم 6 مهندس" +
"ی فناوری اطلاعات دانشگاه صنعتی ارومیه-\r\n                    شماره تماس -09146208" +
"938\r\n                </strong>\r\n            </div>\r\n        </div>\r\n    </div>\r\n" +
"</div>\r\n");

        }
    }
}
#pragma warning restore 1591
