#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MVC5.ViewModel;
    using MVC5.Web;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Index.cshtml")]
    public partial class _Views_Home_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Home_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Home\Index.cshtml"
  
    ViewBag.Title = "Home Page";

            
            #line default
            #line hidden
WriteLiteral("\r\n<hr/>\r\n<div");

WriteLiteral(" class=\"jumbotron\"");

WriteLiteral(">\r\n    <h2>سیستم مدیریت محتوای فروشگاه ساز</h2>\r\n    <p");

WriteLiteral(" class=\"lead\"");

WriteLiteral(@">
        این پروژه بر اساس تمام نکات گفته شده توسط جناب نصیری تهیه شده است
        و دو پروژه ک توسط ایشان ارائه شده بود به علاوه سیستم مدیریت کابران و نقش ها و دسترسی ها به صورت داینامیک
        را ها بنده به این پروژه ها افزوده و در واقع برای ادامه پروژه فروشگاه شهر طلایی من از این قالب استفاده خواهد شد.
        دوستانی که مایل باشند میتوانند با بنده همکاری کنند
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>

    </p>
</div>

");

        }
    }
}
#pragma warning restore 1591
