#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MVC5.Web;
    using StackExchange.Profiling;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Administrator/Views/Role/Create.cshtml")]
    public partial class _Areas_Administrator_Views_Role_Create_cshtml : System.Web.Mvc.WebViewPage<MVC5.ViewModel.AdminArea.Role.AddRoleViewModel>
    {
        public _Areas_Administrator_Views_Role_Create_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Administrator\Views\Role\Create.cshtml"
  
    ViewBag.Title = "درج گروه کاربری کاربری";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n");

            
            #line 8 "..\..\Areas\Administrator\Views\Role\Create.cshtml"
        
            
            #line default
            #line hidden
            
            #line 8 "..\..\Areas\Administrator\Views\Role\Create.cshtml"
         using (Html.BeginForm(MVC.Administrator.Role.ActionNames.Create, MVC.Administrator.Role.Name, new { area =MVC.Administrator.Name }, FormMethod.Post, new { role = "form", @class = "form-horizontal" }))
        {
            
            
            #line default
            #line hidden
            
            #line 10 "..\..\Areas\Administrator\Views\Role\Create.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 10 "..\..\Areas\Administrator\Views\Role\Create.cshtml"
                                    

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n                    <strong>مشخصات گروه</strong>\r\n                </div>\r\n    " +
"            <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 17 "..\..\Areas\Administrator\Views\Role\Create.cshtml"
                   Write(Html.LabelFor(m => m.Name, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 19 "..\..\Areas\Administrator\Views\Role\Create.cshtml"
                       Write(Html.TextBoxFor(m => m.Name, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 20 "..\..\Areas\Administrator\Views\Role\Create.cshtml"
                       Write(Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                   " +
" <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 24 "..\..\Areas\Administrator\Views\Role\Create.cshtml"
                   Write(Html.LabelFor(m => m.Description, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 26 "..\..\Areas\Administrator\Views\Role\Create.cshtml"
                       Write(Html.TextBoxFor(m => m.Description, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 27 "..\..\Areas\Administrator\Views\Role\Create.cshtml"
                       Write(Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                   " +
" <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 col-md-offset-2\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 33 "..\..\Areas\Administrator\Views\Role\Create.cshtml"
                           Write(Html.CheckBoxFor(m => m.IsActive, new { @class = "checkbox-inline" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                ");

            
            #line 34 "..\..\Areas\Administrator\Views\Role\Create.cshtml"
                           Write(Html.LabelFor(m => m.IsActive, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 37 "..\..\Areas\Administrator\Views\Role\Create.cshtml"
                           Write(Html.CheckBoxFor(m => m.IsDefaultForRegister, new { @class = "checkbox-inline" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                ");

            
            #line 38 "..\..\Areas\Administrator\Views\Role\Create.cshtml"
                           Write(Html.LabelFor(m => m.IsDefaultForRegister, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n\r\n         " +
"           </div>\r\n                </div>\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n                    <strong>دسترسی ها</strong>\r\n                </div>\r\n      " +
"          <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(" >\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n");

            
            #line 51 "..\..\Areas\Administrator\Views\Role\Create.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 51 "..\..\Areas\Administrator\Views\Role\Create.cshtml"
                             foreach (var permission in (IEnumerable<SelectListItem>)ViewBag.Permissions)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                ");

WriteLiteral("\r\n                                    <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" type=\"checkbox\"");

WriteAttribute("id", Tuple.Create(" id=\"", 2899), Tuple.Create("\"", 2921)
            
            #line 55 "..\..\Areas\Administrator\Views\Role\Create.cshtml"
, Tuple.Create(Tuple.Create("", 2904), Tuple.Create<System.Object, System.Int32>(permission.Value
            
            #line default
            #line hidden
, 2904), false)
);

WriteLiteral(" name=\"PermissionIds\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2943), Tuple.Create("\"", 2968)
            
            #line 55 "..\..\Areas\Administrator\Views\Role\Create.cshtml"
                                  , Tuple.Create(Tuple.Create("", 2951), Tuple.Create<System.Object, System.Int32>(permission.Value
            
            #line default
            #line hidden
, 2951), false)
);

WriteLiteral(" class=\"checkbox-inline\"");

WriteLiteral(" />\r\n                                        <label");

WriteAttribute("for", Tuple.Create(" for=\"", 3044), Tuple.Create("\"", 3067)
            
            #line 56 "..\..\Areas\Administrator\Views\Role\Create.cshtml"
, Tuple.Create(Tuple.Create("", 3050), Tuple.Create<System.Object, System.Int32>(permission.Value
            
            #line default
            #line hidden
, 3050), false)
);

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">");

            
            #line 56 "..\..\Areas\Administrator\Views\Role\Create.cshtml"
                                                                                        Write(permission.Text);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                                    </div>\r\n                           " +
"     ");

WriteLiteral("\r\n");

            
            #line 59 "..\..\Areas\Administrator\Views\Role\Create.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"panel-footer\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                            <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-success btn-sm btn-block\"");

WriteLiteral(" value=\"ثبت اطلاعات\"");

WriteLiteral(" />\r\n                        </div>\r\n                    </div>\r\n\r\n              " +
"  </div>\r\n            </div>\r\n");

            
            #line 71 "..\..\Areas\Administrator\Views\Role\Create.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
