#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MVC5.Web;
    using StackExchange.Profiling;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Administrator/Views/Role/Edit.cshtml")]
    public partial class _Areas_Administrator_Views_Role_Edit_cshtml : System.Web.Mvc.WebViewPage<MVC5.ViewModel.AdminArea.Role.EditRoleViewModel>
    {
        public _Areas_Administrator_Views_Role_Edit_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
  
    ViewBag.Title = "ویرایش گروه کاربری کاربری";

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n");

            
            #line 9 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
                
            
            #line default
            #line hidden
            
            #line 9 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
                 using (Html.BeginForm(MVC.Administrator.Role.ActionNames.Delete, MVC.Administrator.Role.Name, new { area = MVC.Administrator.Name }, FormMethod.Post, new { role = "form", @class = "form-horizontal" }))
                {
                    
            
            #line default
            #line hidden
            
            #line 11 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
               Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 11 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
                                            
                    
            
            #line default
            #line hidden
            
            #line 12 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
               Write(Html.HiddenFor(a => a.Id));

            
            #line default
            #line hidden
            
            #line 12 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
                                              

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                            <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-danger btn-sm\"");

WriteLiteral(" value=\"حذف گروه کاربری\"");

WriteLiteral(" />\r\n                        </div>\r\n                    </div>\r\n");

            
            #line 18 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n");

            
            #line 25 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
        
            
            #line default
            #line hidden
            
            #line 25 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
         using (Html.BeginForm(MVC.Administrator.Role.ActionNames.Edit, MVC.Administrator.Role.Name, new { area = MVC.Administrator.Name }, FormMethod.Post, new { role = "form", @class = "form-horizontal" }))
        {
            
            
            #line default
            #line hidden
            
            #line 27 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 27 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
                                    
            
            
            #line default
            #line hidden
            
            #line 28 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
       Write(Html.HiddenFor(a => a.Id));

            
            #line default
            #line hidden
            
            #line 28 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
                                      

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n\r\n                    <strong>مشخصات گروه</strong>\r\n                </div>\r\n  " +
"              <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 36 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
                   Write(Html.LabelFor(m => m.Name, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 38 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
                       Write(Html.TextBoxFor(m => m.Name, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 39 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
                       Write(Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                   " +
" <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 43 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
                   Write(Html.LabelFor(m => m.Description, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 45 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
                       Write(Html.TextBoxFor(m => m.Description, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 46 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
                       Write(Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                   " +
" <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-md-2 col-md-offset-2\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 51 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
                       Write(Html.CheckBoxFor(m => m.IsActive, new { @class = "checkbox-inline" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 52 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
                       Write(Html.LabelFor(m => m.IsActive, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 55 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
                       Write(Html.CheckBoxFor(m => m.IsDefaultForRegister, new { @class = "checkbox-inline", @disabled = "disabled" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 56 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
                       Write(Html.LabelFor(m => m.IsDefaultForRegister, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 59 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
                       Write(Html.CheckBoxFor(m => m.IsSystemRole, new { @class = "checkbox-inline", @disabled = "disabled" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 60 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
                       Write(Html.LabelFor(m => m.IsSystemRole, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n\r\n                <" +
"/div>\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n                    <strong>دسترسی ها</strong>\r\n                </div>\r\n      " +
"          <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n");

            
            #line 72 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 72 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
                         foreach (var permission in (IEnumerable<SelectListItem>)ViewBag.Permissions)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            ");

WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" name=\"PermissionIds\"");

WriteAttribute("checked", Tuple.Create(" checked=\"", 3958), Tuple.Create("\"", 3988)
            
            #line 76 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
         , Tuple.Create(Tuple.Create("", 3968), Tuple.Create<System.Object, System.Int32>(permission.Selected
            
            #line default
            #line hidden
, 3968), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 3989), Tuple.Create("\"", 4014)
            
            #line 76 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
                                      , Tuple.Create(Tuple.Create("", 3997), Tuple.Create<System.Object, System.Int32>(permission.Value
            
            #line default
            #line hidden
, 3997), false)
);

WriteLiteral(" class=\"checkbox-inline\"");

WriteLiteral(" />\r\n                                    <label");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">");

            
            #line 77 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
                                                            Write(permission.Text);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                                </div>\r\n                            ");

WriteLiteral("\r\n");

            
            #line 80 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"panel-footer\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                            <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-success btn-sm btn-block\"");

WriteLiteral(" value=\"ثبت اطلاعات\"");

WriteLiteral(" />\r\n\r\n                        </div>\r\n                    </div>\r\n              " +
"  </div>\r\n            </div>\r\n");

            
            #line 92 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
