#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
    using MVC5.Common.Helpers;
    
    #line default
    #line hidden
    using MVC5.Web;
    
    #line 2 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
    using MVC5.Web.RazorHelpers;
    
    #line default
    #line hidden
    using StackExchange.Profiling;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Administrator/Views/Role/Edit.cshtml")]
    public partial class _Areas_Administrator_Views_Role_Edit_cshtml : System.Web.Mvc.WebViewPage<MVC5.ViewModel.AdminArea.Role.EditRoleViewModel>
    {
        public _Areas_Administrator_Views_Role_Edit_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
  
    ViewBag.Title = "ویرایش گروه کاربری کاربری";

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n");

            
            #line 11 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
                
            
            #line default
            #line hidden
            
            #line 11 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
                 using (Html.BeginForm(MVC.Administrator.Role.ActionNames.Delete, MVC.Administrator.Role.Name, new { area = MVC.Administrator.Name }, FormMethod.Post, new { role = "form", @class = "form-horizontal" ,autocomplate="off",id="deleteRoleForm"}))
                {
                    
            
            #line default
            #line hidden
            
            #line 13 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
               Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 13 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
                                            
                    
            
            #line default
            #line hidden
            
            #line 14 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
               Write(Html.HiddenFor(a => a.Id));

            
            #line default
            #line hidden
            
            #line 14 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
                                              

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" onclick=\"AjaxForm.CustomSubmit(this, \'deleteRoleForm\')\"");

WriteLiteral(" data-loading-text=\"در حال ارسال اطلاعات\"");

WriteLiteral(" class=\"btn btn-danger btn-sm\"");

WriteLiteral(">\r\n                            حذف گروه کاربری\r\n                        </button>" +
"\r\n                    </div>\r\n");

            
            #line 20 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n");

            
            #line 27 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
        
            
            #line default
            #line hidden
            
            #line 27 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
         using (Html.BeginForm(MVC.Administrator.Role.ActionNames.Edit, MVC.Administrator.Role.Name, new { area = MVC.Administrator.Name }, FormMethod.Post, new { role = "form", @class = "form-horizontal", autocomplete = "off", id = "editRoleForm" }))
        {
            
            
            #line default
            #line hidden
            
            #line 29 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 29 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
                                    
            
            
            #line default
            #line hidden
            
            #line 30 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
       Write(Html.HiddenFor(a => a.Id));

            
            #line default
            #line hidden
            
            #line 30 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
                                      

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n\r\n                    <strong>مشخصات گروه</strong>\r\n                </div>\r\n  " +
"              <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 38 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
                   Write(Html.LabelFor(m => m.Name, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 40 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
                       Write(Html.NoAutoCompleteTextBoxFor(m => m.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 41 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
                       Write(Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                   " +
" <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 45 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
                   Write(Html.LabelFor(m => m.Description, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 47 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
                       Write(Html.NoAutoCompleteTextBoxFor(m => m.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 48 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
                       Write(Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                   " +
" <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-md-2 col-md-offset-2\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 53 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
                       Write(Html.CheckBoxFor(m => m.IsActive, new { @class = "checkbox-inline" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 54 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
                       Write(Html.LabelFor(m => m.IsActive, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 57 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
                       Write(Html.CheckBoxFor(m => m.IsDefaultForRegister, new { @class = "checkbox-inline", @disabled = "disabled" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 58 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
                       Write(Html.LabelFor(m => m.IsDefaultForRegister, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 61 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
                       Write(Html.CheckBoxFor(m => m.IsSystemRole, new { @class = "checkbox-inline", @disabled = "disabled" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 62 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
                       Write(Html.LabelFor(m => m.IsSystemRole, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n\r\n                <" +
"/div>\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n                    <strong>دسترسی ها</strong>\r\n                </div>\r\n      " +
"          <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n");

WriteLiteral("                   ");

            
            #line 73 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
              Write(CheckBoxListBuilder.CheckBoxList("PermissioinIds", ViewBag.Permissions));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"panel-footer\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" onclick=\"AjaxForm.CustomSubmit(this, \'editRoleForm\')\"");

WriteLiteral(" data-loading-text=\"در حال ارسال اطلاعات\"");

WriteLiteral(" class=\"btn btn-success btn-block\"");

WriteLiteral(">\r\n                                ذخیره تغییرات\r\n                            </b" +
"utton>\r\n                        </div>\r\n                    </div>\r\n            " +
"    </div>\r\n            </div>\r\n");

            
            #line 85 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

            
            #line 89 "..\..\Areas\Administrator\Views\Role\Edit.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
