#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
    using Microsoft.Owin.Security;
    
    #line default
    #line hidden
    using MVC5.ViewModel;
    using MVC5.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/_ExternalLoginsListPartial.cshtml")]
    public partial class _Views_Account__ExternalLoginsListPartial_cshtml : System.Web.Mvc.WebViewPage<MVC5.ViewModel.Account.ExternalLoginListViewModel>
    {
        public _Views_Account__ExternalLoginsListPartial_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
  
    var loginProviders = Context.GetOwinContext().Authentication.GetExternalAuthenticationTypes();
    var authenticationDescriptions = loginProviders as AuthenticationDescription[] ?? loginProviders.ToArray();

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 8 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
 if (authenticationDescriptions.Any())
{

    using (Html.BeginForm(MVC.Account.ActionNames.ExternalLogin, MVC.Account.Name, new { ReturnUrl = Model.ReturnUrl }))
    {
        
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
                                

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" id=\"socialLoginList\"");

WriteLiteral(">\r\n            <p>\r\n");

            
            #line 16 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
                
            
            #line default
            #line hidden
            
            #line 16 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
                 foreach (var p in authenticationDescriptions)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-danger btn-block\"");

WriteAttribute("id", Tuple.Create("  id=\"", 730), Tuple.Create("\"", 757)
            
            #line 18 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
 , Tuple.Create(Tuple.Create("", 736), Tuple.Create<System.Object, System.Int32>(p.AuthenticationType
            
            #line default
            #line hidden
, 736), false)
);

WriteLiteral(" name=\"provider\"");

WriteAttribute("value", Tuple.Create(" value=\"", 774), Tuple.Create("\"", 803)
            
            #line 18 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
                                               , Tuple.Create(Tuple.Create("", 782), Tuple.Create<System.Object, System.Int32>(p.AuthenticationType
            
            #line default
            #line hidden
, 782), false)
);

WriteAttribute("title", Tuple.Create(" title=\"", 804), Tuple.Create("\"", 835)
            
            #line 18 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
                                                                             , Tuple.Create(Tuple.Create("", 812), Tuple.Create<System.Object, System.Int32>(p.Caption
            
            #line default
            #line hidden
, 812), false)
, Tuple.Create(Tuple.Create(" ", 822), Tuple.Create("ورود", 823), true)
, Tuple.Create(Tuple.Create(" ", 827), Tuple.Create("با", 828), true)
, Tuple.Create(Tuple.Create(" ", 830), Tuple.Create("حساب", 831), true)
);

WriteLiteral(">\r\n\r\n                        <span>");

            
            #line 20 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
                         Write(p.AuthenticationType);

            
            #line default
            #line hidden
WriteLiteral("</span> \r\n                        <span");

WriteAttribute("class", Tuple.Create(" class=\"", 931), Tuple.Create("\"", 991)
, Tuple.Create(Tuple.Create("", 939), Tuple.Create("fa", 939), true)
, Tuple.Create(Tuple.Create(" ", 941), Tuple.Create("fa-align-right", 942), true)
, Tuple.Create(Tuple.Create(" ", 956), Tuple.Create("fa-", 957), true)
            
            #line 21 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
, Tuple.Create(Tuple.Create("", 960), Tuple.Create<System.Object, System.Int32>(p.AuthenticationType.ToLower()
            
            #line default
            #line hidden
, 960), false)
);

WriteLiteral("></span>\r\n                    </button>\r\n");

            
            #line 23 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </p>\r\n        </div>\r\n");

            
            #line 26 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
    }
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
