#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MVC5.ViewModel;
    using MVC5.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/AdminMenu.cshtml")]
    public partial class _Views_Account_AdminMenu_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Account_AdminMenu_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Views\Account\AdminMenu.cshtml"
  
   

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n        <strong>سلام کاربر گرامی !</strong>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"panel-body min-height-340\"");

WriteLiteral(">\r\n        <p>\r\n            منوی کاربری، از طریق کلیک بر روی منوی سه سطری کنار عن" +
"وان سایت ظاهر می‌شود.\r\n            خروجی بانک اطلاعاتی سایت با فرمت XML جهت کارب" +
"ران فعال سایت «از اینجا» قابل دریافت است. همچنین برنامه و «پروژه‌ای» نیز برای مط" +
"العه آفلاین آن تدارک دیده شده‌است.\r\n            لطفا اگر قصد انتشار مطالب علمی و" +
" آموزشی همخوان با موضوع سایت و متعلق به خودتان را دارید، از قسمت «ارسال مطلب» اس" +
"تفاده کنید.\r\n            اگر صرفا قصد معرفی مطالب آموزشی مرتبط با موضوع سایت را " +
"که توسط دیگران تهیه شده‌اند، دارید و یا اینکه مطلب خودتان است در سایتی دیگر و عل" +
"اقمند نیستید آن‌را در قسمت مطالب سایت جاری منتشر کنید، لطفا از قسمت «ارسال اشترا" +
"ک‌ها» استفاده نمائید.\r\n            اگر قصد معرفی و تبلیغ کارها، محصولات، برنامه‌" +
"ها، کتاب‌ها، دوره‌های آموزشی، سایت‌های کاری مرتبط و امثال آن را دارید و این محصو" +
"لات قرار نیست رایگان، سورس باز یا به همراه انتشار مقاله‌ای علمی در مورد جزئیات ف" +
"نی تهیه آن‌ها باشند، لطفا از قسمت معرفی «آگهی‌های نویسندگان» سایت استفاده نمائید" +
". به علاوه در قسمت توضیحات «پروفایل شخصی» در سایت نیز می‌توانید جزئیات بیشتری از" +
" کارهای خود یا سایت‌های مرتبط را نیز قرار دهید.\r\n            اگر قصد معرفی و دری" +
"افت بازخورد پروژه‌های خود را دارید و این پروژه‌ها عموما سورس باز یا رایگان هستند" +
"، لطفا از قسمت «ارسال پروژه‌ها» استفاده کنید. برای ایجاد یک پروژه جدید نیاز است " +
"حداقل یک مطلب ارسالی در سایت داشته باشید.\r\n            اگر علاقمندید در مورد مطل" +
"بی خاص پیرامون زمینه کاری سایت جاری، نظرسنجی را ترتیب دهید، لطفا از قسمت «ارسال " +
"نظرسنجی» استفاده نمائید. برای ایجاد یک نظرسنجی جدید باید حداقل یک مطلب ارسالی در" +
" سایت داشته باشید.\r\n            برای ایجاد یک دوره جدید نیاز است حداقل 7 مطلب ار" +
"سالی در سایت داشته باشید. این عدد جهت شناخت اعضاء برای شرکت در دوره‌های شما ضرور" +
"ی است.\r\n            اگر علاقمند هستید که از کلیه تغییرات سایت (مطالب، نظرات، لین" +
"ک‌ها و غیره) آگاه شوید، بهتر است مشترک فید «آخرین تغییرات» سایت شوید.\r\n        <" +
"/p>\r\n    </div>\r\n   \r\n</div>\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
