#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/DisplayEmail.cshtml")]
    public partial class _Views_Account_DisplayEmail_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Account_DisplayEmail_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Account\DisplayEmail.cshtml"
  
    ViewBag.Title = "نمایش ایمیل";

            
            #line default
            #line hidden
WriteLiteral("\r\n<h2>");

            
            #line 4 "..\..\Views\Account\DisplayEmail.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(".</h2>\r\n<div");

WriteLiteral(" class=\"alert alert-info\"");

WriteLiteral(">\r\n\r\n    <p");

WriteLiteral(" class=\"lead\"");

WriteLiteral(">\r\n      صرفا برای نمایش کار این صفحه در نظر گرفته شده است\r\n    </p>\r\n    <p");

WriteLiteral(" class=\"lead\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" class=\"btn btn-info\"");

WriteAttribute("href", Tuple.Create(" href=\"", 245), Tuple.Create("\"", 265)
            
            #line 11 "..\..\Views\Account\DisplayEmail.cshtml"
, Tuple.Create(Tuple.Create("", 252), Tuple.Create<System.Object, System.Int32>(ViewBag.Link
            
            #line default
            #line hidden
, 252), false)
);

WriteLiteral(">تأیید حساب کاربری</a>کاربر گرامی برای فعال سازی حساب خود ، کلیک کنید\r\n    </p>\r\n" +
"\r\n</div>");

        }
    }
}
#pragma warning restore 1591
