#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Account\ReceiveActivatorEmail.cshtml"
    using CaptchaMvc.HtmlHelpers;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Account\ReceiveActivatorEmail.cshtml"
    using MVC5.Common.Helpers;
    
    #line default
    #line hidden
    using MVC5.ViewModel;
    using MVC5.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/ReceiveActivatorEmail.cshtml")]
    public partial class _Views_Account_ReceiveActivatorEmail_cshtml : System.Web.Mvc.WebViewPage<MVC5.ViewModel.Account.ActivationEmailViewModel>
    {
        public _Views_Account_ReceiveActivatorEmail_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Account\ReceiveActivatorEmail.cshtml"
  


            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\r\n");

            
            #line 9 "..\..\Views\Account\ReceiveActivatorEmail.cshtml"
    
            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\Account\ReceiveActivatorEmail.cshtml"
     using (Html.BeginForm(MVC.Account.ActionNames.ReceiveActivatorEmail, MVC.Account.Name, null, FormMethod.Post, new { @class = "form-horizontal", role = "form", id = "receiveActivationEmailForm" ,autocomplete="off"}))
    {
        
            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\Account\ReceiveActivatorEmail.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\Account\ReceiveActivatorEmail.cshtml"
                                

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"col-md-10 col-md-offset-1\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"panel  panel-default\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n                    <strong> دریافت ایمیل فعال سازی</strong>\r\n                " +
"</div>\r\n                <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 19 "..\..\Views\Account\ReceiveActivatorEmail.cshtml"
                   Write(Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 21 "..\..\Views\Account\ReceiveActivatorEmail.cshtml"
                       Write(Html.NoAutoCompleteTextBoxForLtr(m => m.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 22 "..\..\Views\Account\ReceiveActivatorEmail.cshtml"
                       Write(Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n\r\n                 " +
"   <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 27 "..\..\Views\Account\ReceiveActivatorEmail.cshtml"
                   Write(Html.MathCaptcha(MVC.Shared.Views._CaptchaPartial));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"panel-footer\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" onclick=\"AjaxForm.CustomSubmit(this, \'receiveActivationEmailForm\')\"");

WriteLiteral(" data-loading-text=\"در حال ارسال اطلاعات\"");

WriteLiteral(" class=\"btn btn-success btn-block\"");

WriteLiteral(">\r\n                                دریافت ایمیل فعال سازی\r\n                      " +
"      </button>\r\n                        </div>\r\n\r\n                    </div>\r\n " +
"               </div>\r\n            </div>\r\n        </div>\r\n");

            
            #line 42 "..\..\Views\Account\ReceiveActivatorEmail.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 47 "..\..\Views\Account\ReceiveActivatorEmail.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
