#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\App_Code\ToastrBuilder.cshtml"
    using MVC5.Common.Controller.Alerts;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/App_Code/ToastrBuilder.cshtml")]
    public partial class _App_Code_ToastrBuilder_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {

#line 7 "..\..\App_Code\ToastrBuilder.cshtml"
public System.Web.WebPages.HelperResult ShowToastMessages(Toastr toastr)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 8 "..\..\App_Code\ToastrBuilder.cshtml"
 
    if (toastr == null)
    {
        return;
    }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <script>\r\n        $(document).ready(function () {\r\n            toastr.options" +
".closeButton = \'");


#line 15 "..\..\App_Code\ToastrBuilder.cshtml"
            WriteTo(__razor_helper_writer, toastr.ShowCloseButton);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\';\r\n            toastr.options.newestOnTop = \'");


#line 16 "..\..\App_Code\ToastrBuilder.cshtml"
            WriteTo(__razor_helper_writer, toastr.ShowNewestOnTop);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\';\r\n\r\n");


#line 18 "..\..\App_Code\ToastrBuilder.cshtml"
            

#line default
#line hidden

#line 18 "..\..\App_Code\ToastrBuilder.cshtml"
             foreach (var message in toastr.ToastMessages)
            {
                var toastTypeValue = message.AlertType.ToLower();


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "               ");

WriteLiteralTo(__razor_helper_writer, "var optionsOverride = { /* Add message specific options here */ };\r\n");


#line 22 "..\..\App_Code\ToastrBuilder.cshtml"
                if (message.IsSticky)
                {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                    ");

WriteLiteralTo(__razor_helper_writer, "optionsOverride.timeOut = 0;\r\n                    optionsOverride.extendedTimeout" +
" = 0;");

WriteLiteralTo(__razor_helper_writer, "\r\n");


#line 26 "..\..\App_Code\ToastrBuilder.cshtml"
                }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                ");

WriteLiteralTo(__razor_helper_writer, "toastr[\'");


#line 27 "..\..\App_Code\ToastrBuilder.cshtml"
WriteTo(__razor_helper_writer, toastTypeValue);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\'](\'");


#line 27 "..\..\App_Code\ToastrBuilder.cshtml"
               WriteTo(__razor_helper_writer, message.Message);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\', \'");


#line 27 "..\..\App_Code\ToastrBuilder.cshtml"
                                   WriteTo(__razor_helper_writer, message.Title);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\', optionsOverride);\r\n");


#line 28 "..\..\App_Code\ToastrBuilder.cshtml"
            }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        });\r\n    </script>\r\n");


#line 31 "..\..\App_Code\ToastrBuilder.cshtml"


#line default
#line hidden
});

#line 31 "..\..\App_Code\ToastrBuilder.cshtml"
}
#line default
#line hidden

        public _App_Code_ToastrBuilder_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
