#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MVC5.Web;
    
    #line 1 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
    using MVC5.Web.RazorHelpers;
    
    #line default
    #line hidden
    using StackExchange.Profiling;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Administrator/Views/User/Edit.cshtml")]
    public partial class _Areas_Administrator_Views_User_Edit_cshtml : System.Web.Mvc.WebViewPage<MVC5.ViewModel.AdminArea.User.EditUserViewModel>
    {
        public _Areas_Administrator_Views_User_Edit_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
  
    ViewBag.Title = "ویرایش کاربر";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 6 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
 if (!Model.IsSystemAccount)
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n");

            
            #line 12 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 12 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
                     using (Html.BeginForm(MVC.Administrator.User.ActionNames.Delete,
                    MVC.Administrator.User.Name, new { area = MVC.Administrator.Name }, FormMethod.Post, new { role = "form", @class = "form-horizontal", autocomplete = "off", id = "deleteUserForm" }))
                    {
                        
            
            #line default
            #line hidden
            
            #line 15 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
                   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 15 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
                                                
                        
            
            #line default
            #line hidden
            
            #line 16 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
                   Write(Html.HiddenFor(a => a.Id));

            
            #line default
            #line hidden
            
            #line 16 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
                                                  

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" onclick=\"AjaxForm.CustomSubmit(this, \'deleteUserForm\')\"");

WriteLiteral(" data-loading-text=\"در حال ارسال اطلاعات\"");

WriteLiteral(" class=\"btn btn-danger btn-sm\"");

WriteLiteral(">\r\n                                    حذف کاربر\r\n                               " +
" </button>\r\n                            </div>\r\n                        </div>\r\n" +
"");

            
            #line 24 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n");

            
            #line 29 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n");

            
            #line 33 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
        
            
            #line default
            #line hidden
            
            #line 33 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
         using (Html.BeginForm(MVC.Administrator.User.ActionNames.Create, MVC.Administrator.User.Name, new { area = "Administrator" }, FormMethod.Post, new { User = "form", @class = "form-horizontal" ,autocomplate="off",id="editUserForm"}))
        {
            
            
            #line default
            #line hidden
            
            #line 35 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 35 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
                                    
            
            
            #line default
            #line hidden
            
            #line 36 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
       Write(Html.HiddenFor(a => a.Id));

            
            #line default
            #line hidden
            
            #line 36 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
                                      

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n                    <strong>مشخصات کاربر</strong>\r\n                </div>\r\n   " +
"             <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n\r\n                    <ul");

WriteLiteral(" class=\"nav nav-tabs\"");

WriteLiteral(">\r\n                        <li");

WriteLiteral(" class=\"active\"");

WriteLiteral(">\r\n                            <a");

WriteLiteral(" href=\"#requiredInfo\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">مشخصات ضروری</a>\r\n                        </li>\r\n                        <li>\r\n " +
"                           <a");

WriteLiteral(" href=\"#optionalInfo\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">مشخصات اختیاری</a>\r\n                        </li>\r\n                        <li>\r" +
"\n                            <a");

WriteLiteral(" href=\"#permissions\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">دسترسی های جزئی</a>\r\n                        </li>\r\n                        <li>" +
"\r\n                            <a");

WriteLiteral(" href=\"#roles\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">گروه های کاربری</a>\r\n                        </li>\r\n                    </ul>\r\n\r" +
"\n                    <div");

WriteLiteral(" class=\"tab-content\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"tab-pane active\"");

WriteLiteral(" id=\"requiredInfo\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 61 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
                           Write(Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 63 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
                               Write(Html.TextBoxFor(m => m.Email, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 64 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
                               Write(Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                         <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 68 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
                           Write(Html.LabelFor(m => m.UserName, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 70 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
                               Write(Html.TextBoxFor(m => m.UserName, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 71 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
                               Write(Html.ValidationMessageFor(m => m.UserName, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n\r\n " +
"                           <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 76 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
                           Write(Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 78 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
                               Write(Html.TextBoxFor(m => m.Password, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 79 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
                               Write(Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n\r\n " +
"                           <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 84 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
                           Write(Html.LabelFor(m => m.NameForShow, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 86 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
                               Write(Html.TextBoxFor(m => m.NameForShow, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 87 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
                               Write(Html.ValidationMessageFor(m => m.NameForShow, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                     </div>\r\n\r\n                        <div");

WriteLiteral(" class=\"tab-pane\"");

WriteLiteral(" id=\"optionalInfo\"");

WriteLiteral(">\r\n\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 95 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
                           Write(Html.LabelFor(m => m.AdministratorComment, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 97 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
                               Write(Html.TextAreaFor(m => m.AdministratorComment, new { cols = 2, @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 98 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
                               Write(Html.ValidationMessageFor(m => m.AdministratorComment, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n\r\n " +
"                           <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 103 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
                           Write(Html.LabelFor(m => m.BirthDay, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 105 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
                               Write(Html.TextBoxFor(m => m.BirthDay, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 106 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
                               Write(Html.ValidationMessageFor(m => m.BirthDay, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n\r\n " +
"                           <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 111 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
                           Write(Html.LabelFor(m => m.GooglePlusId, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 113 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
                               Write(Html.TextBoxFor(m => m.GooglePlusId, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 114 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
                               Write(Html.ValidationMessageFor(m => m.GooglePlusId, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                         <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 118 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
                           Write(Html.LabelFor(m => m.FaceBookId, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 120 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
                               Write(Html.TextBoxFor(m => m.FaceBookId, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 121 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
                               Write(Html.ValidationMessageFor(m => m.FaceBookId, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                     </div>\r\n\r\n                        <div");

WriteLiteral(" class=\"tab-pane\"");

WriteLiteral(" id=\"permissions\"");

WriteLiteral(">\r\n\r\n                            <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 129 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
                           Write(Html.CheckBoxFor(m => m.IsBanned, new { @class = "checkbox-inline" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                ");

            
            #line 130 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
                           Write(Html.LabelFor(m => m.IsBanned, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 133 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
                           Write(Html.CheckBoxFor(m => m.IsDeleted, new { @class = "checkbox-inline" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                ");

            
            #line 134 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
                           Write(Html.LabelFor(m => m.IsDeleted, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n\r\n                            <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 138 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
                           Write(Html.CheckBoxFor(m => m.CanChangeProfilePicture, new { @class = "checkbox-inline" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                ");

            
            #line 139 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
                           Write(Html.LabelFor(m => m.CanChangeProfilePicture, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 142 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
                           Write(Html.CheckBoxFor(m => m.CanUploadFile, new { @class = "checkbox-inline" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                ");

            
            #line 143 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
                           Write(Html.LabelFor(m => m.CanUploadFile, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 146 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
                           Write(Html.CheckBoxFor(m => m.CanModifyFirsAndLastName, new { @class = "checkbox-inline" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                ");

            
            #line 147 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
                           Write(Html.LabelFor(m => m.CanModifyFirsAndLastName, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n\r\n         " +
"               <div");

WriteLiteral(" class=\"tab-pane\"");

WriteLiteral(" id=\"roles\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 152 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
                       Write(CheckBoxListBuilder.CheckBoxList("RoleIds", ViewBag.Roles));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n\r\n                <" +
"/div>\r\n\r\n                <div");

WriteLiteral(" class=\"panel-footer\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" onclick=\"AjaxForm.CustomSubmit(this, \'editUserForm\')\"");

WriteLiteral(" data-loading-text=\"در حال ارسال اطلاعات\"");

WriteLiteral(" class=\"btn btn-success btn-block\"");

WriteLiteral(">\r\n                                دخیره اطلاعات\r\n                            </b" +
"utton>\r\n                        </div>\r\n                    </div>\r\n            " +
"    </div>\r\n            </div>\r\n");

            
            #line 168 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 172 "..\..\Areas\Administrator\Views\User\Edit.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script>\r\n        $(function () {\r\n            warningBeforeLoad();\r\n      " +
"  })\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
